#!/usr/bin/env python3
#
# HTB-Utils
#
# Tool for hackthebox, to submit flags faster or spawn boxes
# cli-based
#
# Made by nomaisthere


import sys
from cli.main import main

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        sys.exit(130)